---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Git for version control 

Version control keeps files organized and tracks changes over time, making it  
easier for you to reproduce your analyses and to step backward/’undo’ changes as  
needed during the analysis process.  

### Learning objectives

The target audience for this workshop is any researcher looking to improve their  
basic skills with Git. During this workshop, participants will  

- Gain familiarity with Git commands, vocabulary, and basic workflows
- Practice using Git to track changes and recover older file versions
- Use both the command line and a Git client

### Sources
This lesson is adapted in part from the [Software Carpentries][] and [Library Carpentries][] lessons.

Other useful resources for learning Git include:

[Happy Git with R][] - especially useful if you are an R user and new to Git.  
[Think Like a Git][] - I found this most useful once I had some basic Git knowledge  
[Git Cheatsheet][] - some basic and some more advanced commands

[Software Carpentries]: https://swcarpentry.github.io/git-novice/
[Library Carpentries]: https://librarycarpentry.org/lc-git/
[Happy Git with R]: https://happygitwithr.com/
[Think Like a Git]: http://think-like-a-git.net/
[Git Cheatsheet]: https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet

Slides presented during the workshop are available here and give more conceptual  
background into using Git for version control.

## Getting started

*Make sure you've downloaded Git and made a GitHub account before the workshop.  
You'll use the same email used for your GitHub account to configure Git on your 
machine.*

### Git commands

When we use Git with the command line, we use the syntax `$ git verb option`  
where `verb` is the command that we want to run, like `add` or `commit`. 

To get an overview of basic Git commands, run `git` by itself in the shell. You  
should see an output that lists a bunch of different commands with a brief explanation.  

This is not the most useful way of learning to use Git, but it does provide a sense  
for the overall trajectory, starting with simple tasks like creating a working area  
or repository, making and tracking changes, comparing history and status, and eventually  
collaborating and using Git in reproducible workflows.

### Configure Git

The first time you use Git on your computer, you will need to configure some settings,  
including your name and email address. It's useful to use the same user name and  
email you will use with GitHub (or other Git host server, such as GitLab). 

It's also helpful to use the `global` flag to configure these settings for all  
Git activity on this computer on your user account. 

`$ git config --global user.name "Your Username"`  
`$ git config --global user.email "Your email"`

You can also configure your preferred text editor to use with Git.  

To set the text editor to nano on Mac or Linux, use: 

`$ git config --global core.editor "nano -w"`

Check out the [table]() from Software Carpentries for setting other text editors.

[table]: https://swcarpentry.github.io/git-novice/02-setup/index.html#line-endings

Finally, configure the name of the default branch to `main`.

`$ git config --global init.defaultBranch main`

Check the status of your git settings with the `list` option:

`$ git config --list` 

### Initialize a repository

Start by initializing a repository. Choose a reasonable directory to work in, such  
as your Desktop or Documents folder, or perhaps a subfolder like 'temp' or 'workshop'.

To create a Git repository (aka repo), run:

`$ git init practice_repo`

There will not be any output from this command. Move your working directory into  
the new `practice_repo` directory, then list the files, including hidden files:

`$ ls -aF`

You'll see a hidden directory named `.git/`. This directory is what Git the program  
uses to track all of the files in your repository, and all of the changes made to  
those files over time. You will not need to access or modify the `.git` directory,  
but its presence tells you that you've initiated version control over the parent folder.

### Check the project status

One of the useful basic commands is `checkout` which will give you the status of  
your git repo. 

`$ git status`

### Create a README

To start tracking files, you need to create some files! A good one to start with  
is a README file. Including a README in a project repository gives the user some  
guidance about what your repo is all about. The user might be your future self,  
looking back at a project after a few months away. 

Create a README file with your text editor (here we use nano), and add a few lines  
describing your practice repo, then close the editor.

`$ nano readme.md` 

If you use `ls` to list the files in your repo, you'll see `readme.md` listed.  
Note that using the extension `.md` creates a markdown file, rather than text.  

You can use the `cat` command to show the text of the file you just created,   
perhaps something like,  

`"A ReadMe file for my Git practice repo"`

Check the status again. Git now gives you a message that you have an untracked file.  
The output also lets you know the syntax to start tracking that file.  

<p class="text-success">
Note, there's nothing wrong with having untracked files. You might not want Git to  
keep track of large raw data files for example. See 'Ignoring files' below for more  
info.
</p>
## Basic Git workflow

### Modify-Add-Commit

Once you've identified a file you want to track, like the README file, you need to  
take two steps. First, tell Git you want to track the file using the `add` command.

`$ git add readme.md`

This is sometimes referred to as staging the file. Basically, you are telling git  
that you want to keep track of the changes made to this file since the last commit.  

Check the status again, and you will see a new message, stating there are changes  
to be committed in a new file.

The second step is to tell Git to save a snapshot of the staged file(s), using  
the `commit` command:

`$ git commit -m 'Add readme.md'`

The `-m` option stand for `message` and the text in quotes is the commit message.  
A commit message is a short, descriptive, and specific summary of the changes we've  
made since the last commit.  

If we tried to run the `commit` command without the `-m` flag and the message text,  
Git would send us to the text editor with instructions to write a commit message. 

<p class="text-success">
Note, the goal of the commit message is to communicate the context of specific  
changes; the message completes the sentence, 'If applied, this commit will __'.  
A good message is short (<50 characters), but a longer description can also be  
added. Enter a return (blank line) to separate the short subject line from a  
longer message with more details.
</p>

The output from running `commit` shows us that the commit has captured the new file,  
with 1 line of text inserted. The output also shows an alphanumeric string of seven  
characters. This is actually the first seven characters of a longer string that  
identifies the commit. This identifier oro label can be useful in navigating your  
Git history.

The basic Git workflow starts by modifying a file, staging the changes (using `add`),  
and commiting those changes (using `commit`). Repeat this cycle to keep track of  
the changes you make to your files over time.

### Tracking changes

Other Git commands give more ability to assess the changes to your files. 

Start by making another change to the README, by adding another line of text. 

Then, run `git status` to see how Git is tracking those changes. You should see  
a message stating there are changes not staged for commit.

It can be useful to compare the changes, before staging and committing, using `diff`:  

`$ git diff`

The first few lines of the output identify what file is being compared, as well as  
the computer-generated identifiers for the two versions. The last lines show the actual  
changes, with a `+` marker showing the line that has been added. 

You can review the `diff` at this point to understand the changes before committing  
them. Once you verify the changes, use `add` and `commit` to complete the cycle.

`$ git add readme.me  
$ git commit -m 'Add more detail to readme'`

Now that you've made multiple commits, it's a good time to look at the Git log.

`$ git log`

The output lists the commits that have been made to this repository, starting with  
the most recent. Here you can see how the commit messages can be really useful for  
understanding the updates to your project. You also see the full length of the  
alphanumeric identifiers that Git uses to label each commit. 

### Looking backwards

Add a third line of text to the README file and look at the text using `cat`.  
You should have three lines of text, similar to:

`"A Read Me file for the practice_repo`  
`This repo is for demonstration purposes.`  
`Another line of text adds more detail."`  

Remember, the first two lines have been added to the previous commit, so they are  
captured by Git. But the third line you just added is a new modifcation, and has not  
been added (staged) and committed yet. 

You can assess the difference between the changes in the current working directory  
and the last commit using the identifier `HEAD`. `HEAD` refers to the most recent  
commit. So, if you want to compare the current changes to the last commit, you can  
use the following syntax:

`$ git diff HEAD readme.md`

Of course, this is the same as if you used only `git diff readme.md` as we did  
previously. However, you can also compare to earlier commits with the `HEAD` syntax.  

`HEAD~1` refers to the commit before `HEAD`(essentially the next oldest commit).  
`HEAD~2` referst to the commit before `HEAD~1`, again moving one step older. 

`$ git diff HEAD~1 readme.md` will highlight multiple lines of text have changed  
since the commit before the most recent commit. 

The `HEAD` syntax can be useful if you find a change that you want to reverse.  
For example, perhaps you decide the third line you just added to the READEME isn't  
necessary. Remember, that line has not been staged or committed (check with `status`). 

So, you can easily revert the file to the status at the last commit, i.e. `HEAD`:  

`$ git checkout HEAD readme.md`  

The `checkout` command restores the file status to the `HEAD` commit. You could step  
further back using the `HEAD~` syntax or by using the alphanumeric identifiers  
for each commit. The identifiers are long (40 characters) but you can use just the  
first seven characters instead of `HEAD` to refer to a specific commit. 

<p class="text-warning">
Note! Be cautious with using `git checkout`. It can be useful to return to a previous  
version of a file, for example if a script 'breaks' after editing. However, if you  
run `git checkout HEAD` without a filename, you will end up in a 'detached HEAD' state.  
Don't commit changes in this state, instead return to your main branch by running  
`git checkout main`. 
</p>

### Ignoring files

Sometimes there are files in a repository that you do NOT want Git to track, such  
as temporary files created during analysis. 

In the `practice_repo`, create a folder named `temp` for temporary files created  
during analysis, and create some empty files for that folder:

`$ mkdir temp`  

`$ touch temp/a.dat temp/b.dat`  

Git isn't tracking these files yet - because you haven't added them to the staging  
area with `add`. However, having lots of untracked files can clutter up the `status`  
output and generally make things more confusing. 

To specify that we do not want to track these files, we create a `.gitignore` file,  
and we can list these filenames in the `.gitignore`

`$ nano .gitignore`

In the text editor, you can list the exact file names, `a.dat` and `b.dat`, separated  
by a return. Or, you can use a wildcard (*) to indicate all files with names ending  
in `dat` should be tracked.  

`*.dat`

Next, add and commit the `.gitignore` file:

`$ git add .gitignore`  

`$ git commit -m "create .gitignore to ignore .dat files"`

Now, Git will ignore these files when looking for unstaged changes. 

However, you can use the option `-f` to force Git to track a file that is listed  
in the `.gitignore`

`$ git add -f a.dat`

You can also add a directory to a `.gitignore` file, so we could have simply listed  
`temp/` in the `.gitignore` file to exclude all files in the `temp` folder. 

## Using a Git client

An alternative to running Git from the command line is to use a Git client, such  
as GitHub Desktop. The client will give a more visual experience, which can be  
helpful to stay organized as you are learning Git. 

You can download [GitHub Desktop]() if you have not already. When you open the application,  
it will ask you to authenticate using your username and password on GitHub.com.  
If you get stuck, there are [instructions from GitHub here]().

[GitHub Desktop]: https://desktop.github.com/
[instructions from Github here]: https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github

Authenticating with GitHub.com will allow you to collaborate on remote repositories.  
For now, we will focus on using GitHub Desktop to work with the local repo,  
`practice_repo` on your machine. 

### Adding a local repo

To add a local repo to GitHub Desktop, go to `File` and select `Add local repository`.  
Navigate to your `practice_repo` directory (probably on your Desktop) and click  
`Add repository`.

You should now see the repository in the left-hand pane. Click on the repository  
name, and a new left-hand pane appears, showing 'Changes' and 'History'. 

Commits you have made in this repo should appear in the 'History' pane. 

New changes to your files will appear in the 'Changes' pane. 

### Staging and commiting

The strength of using a client like GitHub Desktop is that it provides more visual  
information compared to the shell. For example, in the 'Changes' pane, you should  
see your README file listed, with a check box to the left and a symbol to the right.  
The checkbox shows if your file is staged - it's probably checked if you have staged  
the file in the shell. The symbol will be orange if the file has been modified but  
not commited. 

To make a commit, you enter a commit message at the bottom of the 'Changes' panel  
and click 'Commit to main'

You might need to make a modification to your README file so you have something  
to commit. You can do that back in the shell (using the text editor as before).  
Or, try right-clicking on the filename in the GitHub Desktop pane. You'll see an  
option to open the file (perhaps in RStudio or in the default program). You can edit  
the file in that program, save and close, and you will see new changes to commit  
in GitHub Desktop. 

### Git client vs. command line

Using a Git client vs the command line is a matter of personal preference. The  
visual information from the client can make it much easier to understand what  
is happening with a repo, even if you end up running the Git commands in the shell. 

Take some time to explore the GitHub Desktop functionality. Many of the commands  
covered above are easily accessible. For example, unchecking the checkbox will  
unstage a file, indicating you do not want Git to record new changes in the next  
commit. And if you have an unstaged file, you can right-click and select 'Add to  
gitignore' to ignore that file. This approach can be more intuitive to learn than  
using the command line. 

If you are an R user, RStudio has a basic Git client. You can also access the shell  
within RStudio as well, so it is easy to use both the command line and a client  
to access Git as needed. 

Jenny Bryan, the author of Happy Git for the useR, gives a good run-down of the  
[reasons to use a Git client]().

[reasons to use a Git client]: https://happygitwithr.com/git-client.html

## Exercises

Working in either the command line or a Git client:

 1. Create a new repository named `bio` and initialize version control
 2. Create a text file named `my_bio.txt` and add at least three lines about yourself.
 3. Commit the changes to `my_bio.txt`
 4. Edit `my_bio.txt` by changing one of the previous lines and adding a fourth  
 line of text
 5. Display the differences between the last commit and the updated version
 6. Use the alternative tool (command line or client) to commit the new changes  
 and check the status of the repo
 7. Delete the `bio` repo and contents from your computer using the command line.
