---
title: "Reproducible Research Workshop Series"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
<p class="text-success">
*Note, this site is under construction, with more content to be added soon!*
</p>



### Overview 
This series of workshops will introduce tools and practices for conducting reproducible research with quantitative data. Topics covered include principles of reproducible workflows, using Git for version control and GitHub for collaboration, and best practices for project management. These foundational data science skills can improve research practices across disciplines and support efficient and effective collaboration.

### Audience 
Workshops are open to graduate students, postdocs, and researchers at University of Oregon, Oregon State University, and Portland State University. No programming experience is needed but basic familiarity with any coding language and environment (R, Python, Matlab) will be helpful. The exception is the RMarkdown workshop - basic experience using R and RStudio is highly recommended for this workshop.  

### Schedule {.tabset}

#### Spring 2022

Workshops for Spring 2022 will be held on Tuesdays from 2-4 pm.  

> March 29 - Reproducible Research Workflows  
April 5 - Intro to the Command Line  
April 12 - Git for Version Control  
April 19 - GitHub for Collaboration  
April 26 - Metadata and Data Documentation  
May 3 - Reproducible Reports with RMarkdown  
May 10 - Accessing Data Repositories  
May 17 - Publishing Data and Code  

Workshops are modular - please register and attend any and all sessions that are of interest.   


<button type="button" class="btn btn-primary btn-lg" 
onclick="window.location.href= 'https://uoregon.zoom.us/meeting/register/tJAkdeuurTkjH9w7P6t9mmMq3Gu0VUz3Vt7m';">
Register
</button>    


<!-- <button type="button" class="btn btn-link btn-lg">[Register][]</button>   -->

<!-- [Register]: https://uoregon.zoom.us/meeting/register/tJAkdeuurTkjH9w7P6t9mmMq3Gu0VUz3Vt7m   -->

#### Winter 2022

Workshops for Winter 2022 will be held on Wednesdays from 1-3 pm. 

> Feb 2 - Metadata and Data Documentation  
Feb 9 - Reproducible Reports with RMarkdown  
Feb 16 - Accessing Data Repositories  
Feb 23 - Publishing Data and Code

#### Fall 2021

For the Fall 2021 pilot, we will offer three workshops in the series:

1.	Reproducible Research Workflows
3.	Intro to the Shell and Version Control with Git
4.	Git + GitHub for Collaboration  

In future iterations of the workshop series, we plan to cover additional topics such as using RMarkdown for reproducible reports, metadata and data documentation, and working with external data repositories. We are actively seeking input from the Oregon research community to understand what kinds of training can benefit researchers – suggestions are welcome!

### Location

The workshop format is hybrid - participants can join in-person at UO in Eugene and remotely over Zoom. The in-person location is Pacific Hall 204.  

### Instructor

Workshops are led by Lillian Aoki, data scientist and ecologist at UO's Data Science Initiative. She received her PhD in Environmental Sciences from the University of Virginia where she studied coastal ecosystem restoration and resilience. Her research interests include leveraging datasets across spatial and temporal scales to understand ecosystem dynamics.   

### Workshop descriptions

*Reproducible Research Workflows*  
Reproducibility is central to scientific inquiry. In this workshop, participants will discuss the principles underlying reproducible research (e.g., FAIR data, open science) and consider how to build a reproducible research workflow. Exercises will focus on best practices that facilitate reproducibility and collaboration, such as file and project organization. This is a non-technical workshop (although computational tools will be discussed).

*Intro to the Shell and Version Control with Git*  
Working in the shell is a succinct way to navigate files and run programs and is fundamental for some advanced computing tasks. Version control keeps files organized and tracks changes over time, making it easier for you to reproduce your analyses and to step backward/’undo’ changes as needed during the analysis process. This workshop will first introduce participants to using the command line interface and will build on those skills to practice using Git for version control. We will use both the command line and a Git client to practice basic Git commands and workflow.

*Git + GitHub for Collaboration*  
While version control with Git enhances reproducibility, GitHub takes it to the next level by facilitating collaboration. In this workshop, participants will practice collaborating on GitHub, including pushing and pulling changes to a shared repository. We will also explore some of GitHub’s additional functionality (e.g. using Issues) that can support scientific teams.

*Metadata and Data Documentation*  
Data documentation is a critical step in creating reproducible research but is often overlooked. Through this workshop, participants will learn about different elements of data documentation, including ReadMe files, data dictionaries, and metadata standards. Participants will apply documentation best practices to their own or demonstration data.  

*Reproducible Reports with RMarkdown*  
RMarkdown is a useful extension of the Markdown language that combines text and executable code in one document for literate programming. This workshop will introduce RMarkdown and demonstrate ways to incorporate RMarkdown files into a reproducible workflow, including through collaboration on GitHub. Familiarity with R, RStudio, and GitHub, or participation in earlier workshops, is recommended; the first 20 min of the workshop will include a rapid overview of RStudio and the RStudio interface with Git/GitHub.  

*Accessing Data Repositories*  
In the era of big data and open science, more data are available across a range of fields than ever before. In this workshop, we will cover the basics of accessing different data repositories and discuss best practices for finding, using, and citing publicly available data.  

*Publishing Your Data and Code*  
In many scientific disciplines, it is now common or expected to publish your underlying data and code along with manuscripts (and it is in fact required by many funders). In this workshop, we will discuss different methods of publishing and archiving data and code, including using Zenodo to archive a GitHub repository with a DOI, and identifying appropriate repositories for different types of data.  

### License

This material is available under the [Open Source Initiative][]'s [BSD-3-Clause license][].  
See the full text of the license [here](license.html).

[Open Source Initiative]: https://opensource.org/about
[BSD-3-Clause license]: https://opensource.org/licenses/BSD-3-Clause

### Funding

These workshops are supported by NSF grant OAC-2019161 to the University of Oregon, Oregon State University, and Portland State University
