---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Metadata and data documentation
Data documentation is a critical step in creating reproducible research but is often overlooked. Through this workshop, participants will learn about different elements of data documentation, including ReadMe files, data dictionaries, and metadata standards. Participants will apply documentation best practices to their own or demonstration data.  

### Learning objectives
The target audience for this workshop is any researcher looking to improve their data documentation practices. During the workshop, participants will  

- Understand the purpose and value of different types of metadata  
- Learn about best practices for data documentation  
- Create metadata for their own or a demonstration project  

### Resources

Cornell University Data Management - [README guide + template](https://data.research.cornell.edu/content/readme)  
Dryad - [Good Data Practices](https://datadryad.org/stash/best_practices#describe)  
Environmental Data Initiative - [Best Practices for Keywords](https://environmentaldatainitiative.org/five-phases-of-data-publishing/phase-3/keyword-best-practices/)  
Ecological Metadata Language - [ezEML tool](https://ezeml.edirepository.org/eml/)  
Research Data Alliance - [compilation of metadata standards for different fields](http://rd-alliance.github.io/metadata-directory/standards/)

## Workshop materials  

### Data

During the workshop, participants will practice creating metadata for a project and a tabular dataset. You can either use your own project and data or a demonstration project. The demo project we will use is available from the Knowledge Network for Biocomplexity:  
[Compiled annual statewide Alaskan salmon escapement counts, 1921-2017.](https://knb.ecoinformatics.org/view/urn%3Auuid%3A0255141e-b0b0-4dbe-8586-8838f2ac9048)  

- You will need to download the file ‘CompiledEsc.csv’  
- Keep the repository webpage open during the workshop for easy access to the metadata  

### Slides

[Slides are available here](https://github.com/lillian-aoki/workshop_website/blob/master/slides/05_metadata.pdf)

### Exercises

#### README

Review sample READMEs  

- [Example 1 – University of Arizona](https://osf.io/f46sm/)  
- [Example 2 – Hack for California](https://osf.io/f46sm/)  
- [Example 3 - Kriebel et al. 2018](https://datadryad.org/stash/dataset/doi:10.5061/dryad.j17pm)  
(click on 'October 19, 2018' under 'Download dataset', then click the 'README' link)  

What is effective about these READMEs? What would you change?

#### Data dictionary

For your own project and dataset, use these guidelines to start drafting a data dictionary: 

- List all the variables in the dataset  
- Include a definition, data type, and units  
- Include range or list of accepted values  
- Include missing value codes  

Consider what other information to include, such as flags for quality control.  

Do you encounter any unexpected properties of your data?  

For the demo data, visit the project repository.  

- Scroll down to the “Data Table” details and click through the different attributes  

Are any of the variables unclear? Is any information missing?  

#### Structured metadata standards

Practice building a metadata document using the EML metadata standard.  

- Open the [ezEML tool](https://ezeml.edirepository.org/eml/)   
- Log in with your GitHub, ORCID, or Google account  
- Click ‘EML Documents’ and select ‘New’  
- Enter a name for your EML document – ‘Demo EML document’ or name with your project data  
- Upload a data table – either your own tabular data or the demo CSV  
- Work through the ezEML wizard to enter information and validate the metadata  

What are the most challenging parts of using the metadata standard?  
